# Copyright 2026 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

name: DCO
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  dco-check:
    name: DCO Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.4'

      - name: Run python DCO check
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          
          if [ "$GITHUB_EVENT_NAME" == "merge_group" ]; then
            echo "Skipping DCO check for merge group"
            exit 0
          fi

          python3 .github/scripts/dco_check.py --verbose \
            --exclude-pattern "dependabot\[bot\]@users\.noreply\.github\.com" \
            --exclude-pattern ".*github-actions\[bot\]@users\.noreply\.github\.com"

          if [ $? -ne 0 ]; then
            echo "DCO check failed"
            exit 1
          fi

